apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lkevk15be-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lkevk15be-python 
  name: lkevk15be-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lkevk15be-python 
